# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

picosat_solve <- function(cnf) {
    .Call('Rpicosat_solve', cnf, PACKAGE = 'Rpicosat')
}

picosat.solve <- function(cnf) {
    .Call('Rpicosat_solve', cnf, PACKAGE = 'Rpicosat')
}